---
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts['distribution'] + '-' + ansible_facts['distribution_version'] }}.yml"
    - "{{ ansible_facts['os_family'] + '-' + ansible_facts['distribution_major_version'] }}.yml"
    - "{{ ansible_facts['os_family'] }}.yml"

- name: Set the msmtp_packages variable.
  ansible.builtin.set_fact:
    msmtp_packages: "{{ __msmtp_packages }}"
  when: msmtp_packages is not defined

- name: Update apt cache.
  ansible.builtin.apt:
    update_cache: true
    upgrade: "no"
    cache_valid_time: 14400 # 4 hours
  tags: mail
  when: ansible_os_family == "Debian"

- name: Remove other MTAs.
  ansible.builtin.package:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - exim4*
      - postfix*
      - sendmail*
  tags:
    - mail
  when:
    - msmtp_remove_mtas

- name: Install msmtp packages
  ansible.builtin.package:
    name: "{{ msmtp_packages }}"
    state: present
  tags: mail

- name: Overwrite busybox sendmail link to point to mSMTP.
  ansible.builtin.file:
    src: /usr/bin/msmtp
    dest: /usr/sbin/sendmail
    state: link
  when: ansible_os_family == "Alpine"

- name: Copy mstprc conf file.
  ansible.builtin.template:
    src: msmtprc.j2
    dest: /etc/msmtprc
    owner: "{{ msmtprc_owner }}"
    group: "{{ msmtprc_group }}"
    mode: "{{ msmtprc_mode }}"
  tags: mail

- name: Copy aliases conf file.
  ansible.builtin.template:
    src: aliases.j2
    dest: /etc/aliases
    owner: "{{ msmtprc_owner }}"
    group: "{{ msmtprc_group }}"
    mode: "{{ msmtprc_mode }}"
  tags: mail
